apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: production
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        env:  
        - name: DB_HOST    
          value: "devopscilsy.cbbkbjoitxuc.ap-southeast-1.rds.amazonaws.com"
